#spring.datasource.url: jdbc:h2:file:./camunda-h2-database
#
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    username: camunda
#    password: camunda-change-me
#    url: jdbc:postgresql://localhost:15432/camunda-db

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: Asd,.-123
    url: jdbc:sqlserver://localhost:1433;databaseName=camunda-db;sslProtocol=TLS;encrypt=false;trustServerCertificate=true



camunda:
  bpm:
    authorization:
      enabled: true
    admin-user:
      id: jmarin
      password: Asd,.-123
    deployment-resource-pattern: classpath:processes/*.bpmn, classpath:processes/*.dmn
  initializer:
    populate: classpath:populate/users.csv
  rest-api:
    jwt:
      secret-path: ./src/main/resources/secrets/jwt.pub
      validator-class: com.gedsys.workflow.config.ValidatorJWT