version: "3.9"  # optional since v1.27.0
services:
  camunda-db:
    image: postgres:14.2
    restart: always
    ports:
      - "15432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: ./postgres.env
volumes:
  postgres-data:
      name: camunda-db